-- Migration for New CRM Integration
-- Based on CRM/src/schema.ts

-- Users table is likely handled by Supabase Auth, but we can create a profile extension if needed.
-- Skipping 'users' table creation as ERP uses Supabase Auth.
-- We might need to ensure 'profiles' has necessary fields.

-- Evolution API Configuration
CREATE TABLE IF NOT EXISTS evolution_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id), -- Changed from int to UUID for Supabase
  api_url VARCHAR(500) NOT NULL,
  api_key VARCHAR(500) NOT NULL,
  instance_name VARCHAR(100),
  instance_status VARCHAR(50) DEFAULT 'disconnected', -- Enum as text
  phone_number VARCHAR(20),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- WhatsApp Contacts
CREATE TABLE IF NOT EXISTS crm_contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  remote_jid VARCHAR(100) NOT NULL,
  push_name VARCHAR(255),
  profile_pic_url TEXT,
  phone_number VARCHAR(20),
  name VARCHAR(255),
  email VARCHAR(320),
  company VARCHAR(255),
  notes TEXT,
  tags TEXT,
  funnel_stage VARCHAR(50) DEFAULT 'lead',
  deal_value DECIMAL(12, 2),
  last_message_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- WhatsApp Messages
CREATE TABLE IF NOT EXISTS crm_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  contact_id BIGINT REFERENCES crm_contacts(id),
  message_id VARCHAR(100) NOT NULL,
  remote_jid VARCHAR(100) NOT NULL,
  from_me BOOLEAN DEFAULT FALSE NOT NULL,
  message_type VARCHAR(50) DEFAULT 'text',
  content TEXT,
  media_url TEXT,
  media_mime_type VARCHAR(100),
  media_file_name VARCHAR(255),
  quoted_message_id VARCHAR(100),
  status VARCHAR(20) DEFAULT 'pending',
  timestamp TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Funnel Stages
CREATE TABLE IF NOT EXISTS funnel_stages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(50) NOT NULL,
  color VARCHAR(20) DEFAULT '#6366f1',
  "order" INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Conversations
CREATE TABLE IF NOT EXISTS crm_conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  contact_id BIGINT REFERENCES crm_contacts(id),
  remote_jid VARCHAR(100) NOT NULL,
  unread_count INT DEFAULT 0,
  last_message_preview TEXT,
  last_message_at TIMESTAMPTZ,
  is_archived BOOLEAN DEFAULT FALSE,
  is_pinned BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add indexes for performance (Database Architect)
CREATE INDEX IF NOT EXISTS idx_crm_contacts_user_id ON crm_contacts(user_id);
CREATE INDEX IF NOT EXISTS idx_crm_messages_contact_id ON crm_messages(contact_id);
CREATE INDEX IF NOT EXISTS idx_crm_messages_remote_jid ON crm_messages(remote_jid);
CREATE INDEX IF NOT EXISTS idx_crm_conversations_remote_jid ON crm_conversations(remote_jid);
